name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Descargar el código
        uses: actions/checkout@v4

      - name: 2. Forzar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: 3. Instalar motor Flutter oficial
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: 4. Firmar licencias de Android en el motor
        run: yes | flutter doctor --android-licenses

      - name: 5. Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: 6. Instalar Flet y librerias
        run: pip install flet requests

      - name: 7. Compilar la APK
        run: flet build apk --yes

      - name: 8. Guardar el instalador final
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: build/apk/