name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Descargar el código
        uses: actions/checkout@v4

      - name: 2. Forzar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: 3. Dependencias graficas de Ubuntu
        run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev mesa-utils

      - name: 4. Instalar motor Flutter oficial
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: 5. Firmar licencias de Android
        run: yes | flutter doctor --android-licenses

      - name: 6. Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: 7. Instalar Flet
        run: pip install flet requests

      - name: 8. Compilar la APK
        run: yes | flet build apk --verbose

      - name: 9. Guardar instalador final
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: build/apk/